# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Country.destroy_all

countries = Country.create!([
  { iso: "AFG", name: "Afghanistan", continent: "Asia" },
  { iso: "ALB", name: "Albania", continent: "Europe" },
  { iso: "DZA", name: "Algeria", continent: "Africa" },
  { iso: "AND", name: "Andorra", continent: "Europe" },
  { iso: "AGO", name: "Angola", continent: "Africa" },
  { iso: "ATG", name: "Antigua and Barbuda", continent: "North America" },
  { iso: "ARG", name: "Argentina", continent: "South America" },
  { iso: "ARM", name: "Armenia", continent: "Europe" },
  { iso: "AUS", name: "Australia", continent: "Oceania" },
  { iso: "AUT", name: "Austria", continent: "Europe" },
  { iso: "AZE", name: "Azerbaijan", continent: "Asia" },
  { iso: "BHS", name: "Bahamas", continent: "North America" },
  { iso: "BHR", name: "Bahrain", continent: "Asia" },
  { iso: "BGD", name: "Bangladesh", continent: "Asia" },
  { iso: "BRB", name: "Barbados", continent: "North America" },
  { iso: "BLR", name: "Belarus", continent: "Europe" },
  { iso: "BEL", name: "Belgium", continent: "Europe" },
  { iso: "BLZ", name: "Belize", continent: "North America" },
  { iso: "BEN", name: "Benin", continent: "Africa" },
  { iso: "BTN", name: "Bhutan", continent: "Asia" },
  { iso: "BOL", name: "Bolivia", continent: "South America" },
  { iso: "BIH", name: "Bosnia and Herzegovina", continent: "Europe" },
  { iso: "BWA", name: "Botswana", continent: "Africa" },
  { iso: "BRA", name: "Brazil", continent: "South America" },
  { iso: "BRN", name: "Brunei", continent: "Asia" },
  { iso: "BGR", name: "Bulgaria", continent: "Europe" },
  { iso: "BFA", name: "Burkina Faso", continent: "Africa" },
  { iso: "BDI", name: "Burundi", continent: "Africa" },
  { iso: "CPV", name: "Cabo Verde", continent: "Africa" },
  { iso: "KHM", name: "Cambodia", continent: "Asia" },
  { iso: "CMR", name: "Cameroon", continent: "Africa" },
  { iso: "CAN", name: "Canada", continent: "North America" },
  { iso: "CAF", name: "Central African Republic", continent: "Africa" },
  { iso: "TCD", name: "Chad", continent: "Africa" },
  { iso: "CHL", name: "Chile", continent: "South America" },
  { iso: "CHN", name: "China", continent: "Asia" },
  { iso: "COL", name: "Colombia", continent: "South America" },
  { iso: "COM", name: "Comoros", continent: "Africa" },
  { iso: "COG", name: "Congo", continent: "Africa" },
  { iso: "COD", name: "Congo (Democratic Republic)", continent: "Africa" },
  { iso: "CRI", name: "Costa Rica", continent: "North America" },
  { iso: "CIV", name: "Côte d’Ivoire", continent: "Africa" },
  { iso: "HRV", name: "Croatia", continent: "Europe" },
  { iso: "CUB", name: "Cuba", continent: "North America" },
  { iso: "CYP", name: "Cyprus", continent: "Europe" },
  { iso: "CZE", name: "Czechia", continent: "Europe" },
  { iso: "DNK", name: "Denmark", continent: "Europe" },
  { iso: "DJI", name: "Djibouti", continent: "Africa" },
  { iso: "DMA", name: "Dominica", continent: "North America" },
  { iso: "DOM", name: "Dominican Republic", continent: "North America" },
  { iso: "ECU", name: "Ecuador", continent: "South America" },
  { iso: "EGY", name: "Egypt", continent: "Africa" },
  { iso: "SLV", name: "El Salvador", continent: "North America" },
  { iso: "GNQ", name: "Equatorial Guinea", continent: "Africa" },
  { iso: "ERI", name: "Eritrea", continent: "Africa" },
  { iso: "EST", name: "Estonia", continent: "Europe" },
  { iso: "SWZ", name: "Eswatini", continent: "Africa" },
  { iso: "ETH", name: "Ethiopia", continent: "Africa" },
  { iso: "FJI", name: "Fiji", continent: "Oceania" },
  { iso: "FIN", name: "Finland", continent: "Europe" },
  { iso: "FRA", name: "France", continent: "Europe" },
  { iso: "GUF", name: "French Guiana", continent: "South America" },
  { iso: "GAB", name: "Gabon", continent: "Africa" },
  { iso: "GMB", name: "Gambia", continent: "Africa" },
  { iso: "GEO", name: "Georgia", continent: "Europe" },
  { iso: "DEU", name: "Germany", continent: "Europe" },
  { iso: "GHA", name: "Ghana", continent: "Africa" },
  { iso: "GRC", name: "Greece", continent: "Europe" },
  { iso: "GRD", name: "Grenada", continent: "North America" },
  { iso: "GTM", name: "Guatemala", continent: "North America" },
  { iso: "GIN", name: "Guinea", continent: "Africa" },
  { iso: "GNB", name: "Guinea-Bissau", continent: "Africa" },
  { iso: "GUY", name: "Guyana", continent: "South America" },
  { iso: "HTI", name: "Haiti", continent: "North America" },
  { iso: "HND", name: "Honduras", continent: "North America" },
  { iso: "HUN", name: "Hungary", continent: "Europe" },
  { iso: "ISL", name: "Iceland", continent: "Europe" },
  { iso: "IND", name: "India", continent: "Asia" },
  { iso: "IDN", name: "Indonesia", continent: "Asia" },
  { iso: "IRN", name: "Iran", continent: "Asia" },
  { iso: "IRQ", name: "Iraq", continent: "Asia" },
  { iso: "IRL", name: "Ireland", continent: "Europe" },
  { iso: "ISR", name: "Israel", continent: "Asia" },
  { iso: "ITA", name: "Italy", continent: "Europe" },
  { iso: "JAM", name: "Jamaica", continent: "North America" },
  { iso: "JPN", name: "Japan", continent: "Asia" },
  { iso: "JOR", name: "Jordan", continent: "Asia" },
  { iso: "KAZ", name: "Kazakhstan", continent: "Asia" },
  { iso: "KEN", name: "Kenya", continent: "Africa" },
  { iso: "KIR", name: "Kiribati", continent: "Oceania" },
  { iso: "PRK", name: "Korea (North)", continent: "Asia" },
  { iso: "KOR", name: "Korea (South)", continent: "Asia" },
  { iso: "KWT", name: "Kuwait", continent: "Asia" },
  { iso: "KGZ", name: "Kyrgyzstan", continent: "Asia" },
  { iso: "LAO", name: "Laos", continent: "Asia" },
  { iso: "LVA", name: "Latvia", continent: "Europe" },
  { iso: "LBN", name: "Lebanon", continent: "Asia" },
  { iso: "LSO", name: "Lesotho", continent: "Africa" },
  { iso: "LBR", name: "Liberia", continent: "Africa" },
  { iso: "LBY", name: "Libya", continent: "Africa" },
  { iso: "LIE", name: "Liechtenstein", continent: "Europe" },
  { iso: "LTU", name: "Lithuania", continent: "Europe" },
  { iso: "LUX", name: "Luxembourg", continent: "Europe" },
  { iso: "MDG", name: "Madagascar", continent: "Africa" },
  { iso: "MWI", name: "Malawi", continent: "Africa" },
  { iso: "MYS", name: "Malaysia", continent: "Asia" },
  { iso: "MDV", name: "Maldives", continent: "Asia" },
  { iso: "MLI", name: "Mali", continent: "Africa" },
  { iso: "MLT", name: "Malta", continent: "Europe" },
  { iso: "MHL", name: "Marshall Islands", continent: "Oceania" },
  { iso: "MRT", name: "Mauritania", continent: "Africa" },
  { iso: "MUS", name: "Mauritius", continent: "Africa" },
  { iso: "MEX", name: "Mexico", continent: "North America" },
  { iso: "FSM", name: "Micronesia", continent: "Oceania" },
  { iso: "MDA", name: "Moldova", continent: "Europe" },
  { iso: "MCO", name: "Monaco", continent: "Europe" },
  { iso: "MNG", name: "Mongolia", continent: "Asia" },
  { iso: "MNE", name: "Montenegro", continent: "Europe" },
  { iso: "MAR", name: "Morocco", continent: "Africa" },
  { iso: "MOZ", name: "Mozambique", continent: "Africa" },
  { iso: "MMR", name: "Myanmar", continent: "Asia" },
  { iso: "NAM", name: "Namibia", continent: "Africa" },
  { iso: "NRU", name: "Nauru", continent: "Oceania" },
  { iso: "NPL", name: "Nepal", continent: "Asia" },
  { iso: "NLD", name: "Netherlands", continent: "Europe" },
  { iso: "NZL", name: "New Zealand", continent: "Oceania" },
  { iso: "NIC", name: "Nicaragua", continent: "North America" },
  { iso: "NER", name: "Niger", continent: "Africa" },
  { iso: "NGA", name: "Nigeria", continent: "Africa" },
  { iso: "MKD", name: "North Macedonia", continent: "Europe" },
  { iso: "NOR", name: "Norway", continent: "Europe" },
  { iso: "OMN", name: "Oman", continent: "Asia" },
  { iso: "PAK", name: "Pakistan", continent: "Asia" },
  { iso: "PLW", name: "Palau", continent: "Oceania" },
  { iso: "PAN", name: "Panama", continent: "North America" },
  { iso: "PNG", name: "Papua New Guinea", continent: "Oceania" },
  { iso: "PRY", name: "Paraguay", continent: "South America" },
  { iso: "PER", name: "Peru", continent: "South America" },
  { iso: "PHL", name: "Philippines", continent: "Asia" },
  { iso: "POL", name: "Poland", continent: "Europe" },
  { iso: "PRT", name: "Portugal", continent: "Europe" },
  { iso: "QAT", name: "Qatar", continent: "Asia" },
  { iso: "ROU", name: "Romania", continent: "Europe" },
  { iso: "RUS", name: "Russia", continent: "Asia, Europe" },
  { iso: "RWA", name: "Rwanda", continent: "Africa" },
  { iso: "KNA", name: "Saint Kitts and Nevis", continent: "North America" },
  { iso: "LCA", name: "Saint Lucia", continent: "North America" },
  { iso: "VCT", name: "Saint Vincent and the Grenadines", continent: "North America" },
  { iso: "WSM", name: "Samoa", continent: "Oceania" },
  { iso: "SMR", name: "San Marino", continent: "Europe" },
  { iso: "STP", name: "Sao Tome and Principe", continent: "Africa" },
  { iso: "SAU", name: "Saudi Arabia", continent: "Asia" },
  { iso: "SEN", name: "Senegal", continent: "Africa" },
  { iso: "SRB", name: "Serbia", continent: "Europe" },
  { iso: "SYC", name: "Seychelles", continent: "Africa" },
  { iso: "SLE", name: "Sierra Leone", continent: "Africa" },
  { iso: "SGP", name: "Singapore", continent: "Asia" },
  { iso: "SVK", name: "Slovakia", continent: "Europe" },
  { iso: "SVN", name: "Slovenia", continent: "Europe" },
  { iso: "SLB", name: "Solomon Islands", continent: "Oceania" },
  { iso: "SOM", name: "Somalia", continent: "Africa" },
  { iso: "ZAF", name: "South Africa", continent: "Africa" },
  { iso: "SSD", name: "South Sudan", continent: "Africa" },
  { iso: "ESP", name: "Spain", continent: "Europe" },
  { iso: "LKA", name: "Sri Lanka", continent: "Asia" },
  { iso: "SDN", name: "Sudan", continent: "Africa" },
  { iso: "SUR", name: "Suriname", continent: "South America" },
  { iso: "SWE", name: "Sweden", continent: "Europe" },
  { iso: "CHE", name: "Switzerland", continent: "Europe" },
  { iso: "SYR", name: "Syria", continent: "Asia" },
  { iso: "TWN", name: "Taiwan", continent: "Asia" },
  { iso: "TJK", name: "Tajikistan", continent: "Asia" },
  { iso: "TZA", name: "Tanzania", continent: "Africa" },
  { iso: "THA", name: "Thailand", continent: "Asia" },
  { iso: "TLS", name: "Timor-Leste", continent: "Asia" },
  { iso: "TGO", name: "Togo", continent: "Africa" },
  { iso: "TON", name: "Tonga", continent: "Oceania" },
  { iso: "TTO", name: "Trinidad and Tobago", continent: "North America" },
  { iso: "TUN", name: "Tunisia", continent: "Africa" },
  { iso: "TUR", name: "Turkey", continent: "Asia, Europe" },
  { iso: "TKM", name: "Turkmenistan", continent: "Asia" },
  { iso: "TUV", name: "Tuvalu", continent: "Oceania" },
  { iso: "UGA", name: "Uganda", continent: "Africa" },
  { iso: "UKR", name: "Ukraine", continent: "Europe" },
  { iso: "ARE", name: "United Arab Emirates", continent: "Asia" },
  { iso: "GBR", name: "United Kingdom", continent: "Europe" },
  { iso: "USA", name: "United States", continent: "North America" },
  { iso: "URY", name: "Uruguay", continent: "South America" },
  { iso: "UZB", name: "Uzbekistan", continent: "Asia" },
  { iso: "VUT", name: "Vanuatu", continent: "Oceania" },
  { iso: "VAT", name: "Vatican City", continent: "Europe" },
  { iso: "VEN", name: "Venezuela", continent: "South America" },
  { iso: "VNM", name: "Vietnam", continent: "Asia" },
  { iso: "YEM", name: "Yemen", continent: "Asia" },
  { iso: "ZMB", name: "Zambia", continent: "Africa" },
  { iso: "ZWE", name: "Zimbabwe", continent: "Africa" }
])
p "Created #{Country.count} countries"

countries.each do |data|
  Country.find_or_create_by!(iso: data[:iso]) do |country|
    country.name = data[:name]
  end
end
